<?php
/**
 * Atwix
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.

 * @category    Atwix Mod
 * @package     Atwix_Jig
 * @author      Atwix Core Team
 * @copyright   Copyright (c) 2012 Atwix (http://www.atwix.com)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
/**
 * @var $this Atwix_Jig_Block_Adminhtml_System_Config_Kitchen
 */
?>

<div class="jig-subsection">
    <h4>Generate products fixtures</h4>
    <div id="kitchen-notices"></div>
    <?php echo $this->__('Generate a test set of products inside of existing category with ability to remove them in future in one click'); ?>
    <span class="jig-status-hint">Currenly generated products:
        <span id="jig-products-generated-count"><?php echo $this->getGeneratedProductsCount() ?></span>
    </span>
    <table class="form-list-inside">
        <tr>
            <td class="label"><label for="jig-products-category-id"><?php echo $this->__('Category Id:') ?></label></td>
            <td class="value">
                <input id="jig-products-category-id" class="input-text" value="" name="jig-products-category-id">
                <p class="note">
                    <span><?php echo $this->__('The test products set will be created in this category') ?></span>
                </p>
            </td>
        </tr>
        <tr>
            <td class="label"><label for="jig-products-category-id"><?php echo $this->__('Include Subcategories:') ?></label></td>
            <td class="value">
                <select id="jig-products-include-subcats" name="jig-products-include-subcats" class="select">
                    <option value="1" selected="selected">Yes</option>
                    <option value="0">No</option>
                </select>
                <p class="note">
                    <span>
                        <?php echo $this->__('Also generate products inside of subcategories of the choosed category') ?>
                    </span>
                </p>
            </td>
        </tr>
    </table>
    <button style="" onclick="" class="scalable add" type="button" id="jig_generate_products">
        <span><span><span>Generate products fixtures</span></span></span>
    </button>
</div>
<?php if ($this->getGeneratedProductsCount() > 0) : ?>
<div class="jig-subsection">
    <h4>Remove products fixtures</h4>
    <div><?php echo $this->__('Remove previously generated test set of products'); ?></div>
    <button style="" onclick="" class="scalable delete" type="button" id="jig_remove_products">
        <span><span><span>Remove products fixtures</span></span></span>
    </button>
</div>
<?php endif ?>

<?php $helper = Mage::helper('atwix_jig') ?>
<?php $websiteId =  $helper->getCurrentWebsite() ?>
<?php $actionUrl = $helper->getKitchenActionUrl('generateproducts') ?>
<script type="text/javascript">
//<![CDATA[
    var atwixJig = new atwixJigKitchen();
    $('jig_generate_products').observe('click', function() {
        atwixJig.generateProducts('<?php echo $actionUrl ?>', '<?php echo $websiteId ?>');
    });
//]]>
</script>
